// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShelterApi.Models;

#nullable disable

namespace PetShelterApi.Migrations
{
    [DbContext(typeof(PetShelterApiContext))]
    [Migration("20230120170209_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("ShelterDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.Property<string>("SubSpecies")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 7,
                            Name = "Denna",
                            ShelterDate = "01/20/2023",
                            Species = "Cat",
                            SubSpecies = "Himalayan"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 2,
                            Name = "Kvothe",
                            ShelterDate = "12/20/2022",
                            Species = "Dog",
                            SubSpecies = "Borzoi"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 5,
                            Name = "Haliax",
                            ShelterDate = "01/03/2023",
                            Species = "Dog",
                            SubSpecies = "Poodle"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 5,
                            Name = "Bast",
                            ShelterDate = "01/10/2023",
                            Species = "Cat",
                            SubSpecies = "Domestic Shorthair"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 10,
                            Name = "OreSeur",
                            ShelterDate = "12/15/2023",
                            Species = "Dog",
                            SubSpecies = "Wolfhound"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 4,
                            Name = "Elend",
                            ShelterDate = "01/10/2023",
                            Species = "Dog",
                            SubSpecies = "Jack Russel Terrier"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 3,
                            Name = "Kjelvin",
                            ShelterDate = "01/18/2023",
                            Species = "Cat",
                            SubSpecies = "Abyssinian"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
